### ISSUE TITLE
Apostrophes are added to string

### ISSUE THREAD

**Issue by Nodonisko** [prscX/react-native-morphing-text#3]
Hi,
apostrophes are added to every string and I am not able to find way how to disable it. Any ideas?

**Comment by prscX** [comment]
Thanks @Nodonisko for raising the issue.

Is it possible to share the screenshot of the issue. I am not able to visualize the issue.

Thanks
</ Pranav >

**Comment by javier-artiles** [comment]
Hi @prscX , I have observed the same issue. The double quotes are present whether the passed text is an empty or non-empty string.
<img width="55" alt="screenshot 2018-04-15 14 36 22" src="https://user-images.githubusercontent.com/6756638/38783681-63712ff8-40ba-11e8-8c79-9359eebd47b3.png">
<img width="145" alt="screenshot 2018-04-15 14 39 51" src="https://user-images.githubusercontent.com/6756638/38783777-faf5c54a-40bb-11e8-9426-a42da64f674c.png">

The issue seems to be the use of `JSON.stringify` in https://github.com/prscX/react-native-morphing-text/blob/57de633851d096ca1509fd772bbd56f6b8acb45d/RNMorphingText.js#L27 and https://github.com/prscX/react-native-morphing-text/blob/57de633851d096ca1509fd772bbd56f6b8acb45d/RNMorphingText.js#L38

**Comment by javier-artiles** [comment]
Oh, I just tried to send a PR but permissions are blocked.
Anyway, below there's the change I suggest. Of course this assumes that the child prop is a single string, which I'd say is pretty reasonable, but of course more robust code can be written to handle non string props.

```
diff --git a/Example/App.js b/Example/App.js
index ce71369..3cd7f14 100644
--- a/Example/App.js
+++ b/Example/App.js
@@ -34,7 +34,7 @@ export default class App extends Component<Props> {
     return <View style={styles.container}>
         <Text>Text 1</Text>
         <RNMorphingText effect={"scale"} width={100} height={100} size={20} color={"#2772ae"}>
-          {this.state.value}
+          {this.state.value.toString()}
         </RNMorphingText>
         <Text>Text 2</Text>
       </View>;
diff --git a/RNMorphingText.js b/RNMorphingText.js
index 04ae060..9927500 100644
--- a/RNMorphingText.js
+++ b/RNMorphingText.js
@@ -24,7 +24,7 @@ class RNMorphingText extends Component {
         return (
             <MorphingText
                 style={{ width: this.props.width, height: this.props.height }}
-                value={JSON.stringify(this.props.children)}
+                value={this.props.children}
                 effect={this.props.effect}
                 color={this.props.color}
                 size={this.props.size}
@@ -35,7 +35,7 @@ class RNMorphingText extends Component {
             <MorphingText
                 style={{ width: this.props.width, height: this.props.height }}
                 props={{
-                    value: JSON.stringify(this.props.children),
+                    value: this.props.children,
                     effect: this.props.effect,
                     color: this.props.color,
                     colorSpace: this.props.colorSpace,
```

**Comment by prscX** [comment]
Thanks @javier-artiles for sharing the solution. Not sure why you are not able to raise PR, I have not set any defined permission. However I will do the suggested changes.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @javier-artiles + @Nodonisko,

I have made the suggested changes. Can you please install [V0.0.3](https://github.com/prscX/react-native-morphing-text/releases/tag/v0.0.3) and verify the same.

Please let me know incase you still face the same issue.

Thanks
</ Pranav >
